# Generated by Django 5.0.1 on 2024-03-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
