stages:
  - install_deps
  - test
  - sonarcloud
  - deploy

default:
  image: node:18-alpine
  before_script:
    - yarn install

Install Dependencies:
  stage: install_deps
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules
  script:
    - yarn install

Test:
  stage: test
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules
  script:
    - yarn test --coverage --coverageDirectory=./coverage --testResultsProcessor=jest-sonar-reporter --collectCoverage=true
    - echo "Unit tests complete."
  artifacts:
    paths:
      - $CI_PROJECT_DIR/coverage
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'

Sonar Cloud Check:
  before_script:
    # to skip default before_script
    - echo "Start Sonar Cloud Check..."
  stage: sonarcloud
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  script:
    - sonar-scanner
  needs:
    - job: Test
      artifacts: true
  allow_failure: true

Eas Build:
  stage: deploy
  script:
    - apk add --no-cache bash
    - npm install
    - export EAS_NO_VCS=1
    - npx eas-cli build --platform all --non-interactive --no-wait --profile preview
  only:
    - main
